[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
lib_deps =
    bblanchon/ArduinoJson
    Links2004/WebSockets
    knolleary/PubSubClient
    adafruit/Adafruit_VL53L0X

[env:esp32dev-http]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
lib_deps =
    bblanchon/ArduinoJson
    adafruit/Adafruit_VL53L0X
build_src_filter = +<http/main_http.cpp> +<sensors.cpp> +<autonomy.cpp>