[platformio]
default_envs = esp32dev

[env]
monitor_speed = 115200
lib_deps =
    bblanchon/ArduinoJson
    adafruit/Adafruit_VL53L0X

[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
lib_deps =
    ${env.lib_deps}
    Links2004/WebSockets
    knolleary/PubSubClient
build_src_filter = +<*> -<main_http.cpp>

[env:esp32dev-http]
platform = espressif32
board = esp32dev
framework = arduino
lib_deps = ${env.lib_deps}
build_src_filter = +<main_http.cpp> +<sensors.cpp> +<autonomy.cpp> -<main.cpp>
