[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200

; First upload via USB, then OTA:
; pio run -t upload --upload-port 192.168.1.x
upload_protocol = espota

lib_deps =
    bblanchon/ArduinoJson @ ^7.0.0
    Links2004/WebSockets @ ^2.4.0
    knolleary/PubSubClient @ ^2.8
