[env:esp32dev]
platform = espressif32 @ ^6.9.0
board = esp32dev
framework = arduino
monitor_speed = 115200
board_build.arduino = esp32dev

lib_deps =
    bblanchon/ArduinoJson @ ^7.0.0
    Links2004/WebSockets @ ^2.4.1
    knolleary/PubSubClient @ ^2.8.0
